version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      major:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-major"
